// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Bo8M51KWAZiJHe9aFaIin_FEOicRfgE',
    appId: '1:780798335842:web:e62dd111ecf92892522a3b',
    messagingSenderId: '780798335842',
    projectId: 'loja-virtual-41ee4',
    authDomain: 'loja-virtual-41ee4.firebaseapp.com',
    storageBucket: 'loja-virtual-41ee4.appspot.com',
    measurementId: 'G-XQD5Z0P1GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEkf2AAQ9yeW529Owz_YDSPWlev5Unsk0',
    appId: '1:780798335842:android:234264675e37f691522a3b',
    messagingSenderId: '780798335842',
    projectId: 'loja-virtual-41ee4',
    storageBucket: 'loja-virtual-41ee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP2i4w-fkGUB4l5q-8JqrHnbGXFroURGo',
    appId: '1:780798335842:ios:9ba9d574221c98e4522a3b',
    messagingSenderId: '780798335842',
    projectId: 'loja-virtual-41ee4',
    storageBucket: 'loja-virtual-41ee4.appspot.com',
    iosClientId: '780798335842-p55bknqda2m4ruv3piggri3bets477vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP2i4w-fkGUB4l5q-8JqrHnbGXFroURGo',
    appId: '1:780798335842:ios:9ba9d574221c98e4522a3b',
    messagingSenderId: '780798335842',
    projectId: 'loja-virtual-41ee4',
    storageBucket: 'loja-virtual-41ee4.appspot.com',
    iosClientId: '780798335842-p55bknqda2m4ruv3piggri3bets477vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtual',
  );
}
